### PR TITLE
Redirect link scripts

### PR DESCRIPTION
**Pull request by jakirkham**
- Pulls in PR ( https://github.com/conda-forge/ipyleaflet-feedstock/pull/5 ).
- Redirects to `.messages.txt` to aid in debugging bad installs.

### CODE REVIEW

**Comment by jakirkham** [comment]
Can clean up a bit after PR ( https://github.com/conda-forge/ipyleaflet-feedstock/pull/8 ) is merged.

**Comment by jakirkham** [comment]
Merged re-rendering PR ( https://github.com/conda-forge/ipyleaflet-feedstock/pull/10 ) and cleaned that content out of this PR. Should be ready to go.

**Comment by jakirkham** [comment]
Is this still needed? Should I try to resolve conflicts?

**Comment by SylvainCorlay** [comment]
Closing as post-link scripts will not be necessary for widget libraries after we require notebook > 5.4

**Pull request closed without merging**
