### PR TITLE
Adding @ellisonbg as a maintainer

### PR DESCRIPTION
**Pull request by SylvainCorlay**
As discussed in person with @ellisonbg.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@SylvainCorlay don't send PRs from master as it will trigger the build and upload. We need to fork to ensure that the PR build won't make into the channel unless we merge it.

PS: I am merging this anyways as this change does not bump the build number and the change does not really needs a re-build.

**Comment by SylvainCorlay** [comment]
Hum sorry my origin was wrongly set to be the same as my upstream :)

**Comment by ocefpaf** [comment]
We've all done that BTW :smile:

**Comment by jakirkham** [comment]
Basically, what @ocefpaf is saying is we need to fork feedstocks and push changes to our fork, which we then PR back here. The reason is all branches on the main feedstock auto-deploy.

There is a proposal that has gotten a fair bit of support to require branches that are intend to do releases to be explicitly listed ( https://github.com/conda-forge/conda-forge.github.io/issues/87 ). In this scheme, `master` would be added to the list, but nothing else. This would avoid these sorts of surprises. Also, it would potentially allow people to potentially edit in the browser. This would significantly cutdown the barrier to making changes. However, I don't think anyone has had time to implement it yet.

**Comment by jakirkham** [comment]
The reason this scheme exists is we have some feedstocks that support multiple versions. They do this by having multiple branches. Though this use case is relatively uncommon. So making it a slightly more difficult (there is no difficulty now) to have multiple versions on a feedstock seems ok. It is sort of like asking for confirmation. 😄

**Pull request merged**
