### PR TITLE
Fix windows tests

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martinRenou** [comment]
@davidbrochart were they not working before? Should we apply this change to other widgets feedstocks?

**Comment by davidbrochart** [comment]
As soon as the first Windows test passed, the other ones were skipped. If this pattern exists somewhere else, we should fix it.

**Comment by martinRenou** [comment]
I see. Thanks. Yeah, we did this in other widgets libraries.

**Comment by davidbrochart** [comment]
It seems unneeded, but it's the rule.

**Comment by martinRenou** [comment]
I mean I understand that it's the rule when you change a dependency, or should the build in any way. But this is just testing. Is it fine to not change it?

**Comment by davidbrochart** [comment]
I had the same questioning, and was about to keep the same build number. I guess it's fine, but it doesn't hurt to increment it anyway.

**Pull request merged**
