### PR TITLE
squelch link script output

### PR DESCRIPTION
**Pull request by bollwyvl**
Nobody likes the output from the post-link scripts from `jupyter nbextension enable`. This redirects any such output.

I'll be doing these for the other extensions as well :)

### CODE REVIEW

**Comment by jakirkham** [comment]
This is under discussion. ( https://github.com/conda-forge/conda-forge.github.io/issues/173 )

**Comment by jakirkham** [comment]
LGTM, but may need a build number bump and some conflicts resolved.

**Comment by SylvainCorlay** [comment]
Closing as post-link scripts will not be necessary for widget libraries after we require notebook > 5.4

**Comment by jasongrout** [comment]
Just curious, when are you planning to require notebook > 5.4?

**Comment by SylvainCorlay** [comment]
> Just curious, when are you planning to require notebook > 5.4?

I guess that we could do it anytime, but it would be annoying for some people. 

These GH issues that are closed were over a year old.

**Comment by jasongrout** [comment]
> I guess that we could do it anytime, but it would be annoying for some people.

I think we ought to do it when we release 8.0 (this summer or later?)

**Pull request closed without merging**
